@startuml 

skinparam {
  DPI 200 
  Shadowing False 
  DefaultFontName Arial 
  ArrowThickness 2
  BorderThickness 1
  linetype polyline
}

skinparam Class {
  Padding 20 
  FontSize 16
  FontColor #595959
  
  header {
    BackgroundColor #BFBFBF
  }
}

skinparam Note {
  BackgroundColor #FFE296
  FontColor #8E724B
  BorderColor #8E724B
}

skinparam CircledCharacter {
  FontName Monospace
  FontSize 10 
  FontStyle bold
  FontColor #777777
}

skinparam ClassBorderColor<<emphasized>> red 
skinparam ClassBorderThickness<<emphasized>> 3

hide empty methods 
hide empty attributes

@enduml
