@startuml 

skinparam {
  DPI 200 
  Shadowing False 
  DefaultFontName Arial 
  linetype polyline
}

skinparam CircledCharacter {
  FontName Monospace
  FontSize 10 
  FontStyle bold
  FontColor #777777
}

hide empty methods 
hide empty attributes

@enduml
